MOUSEKEY_ENABLE = no    # Mouse keys
OLED_ENABLE     = yes
LTO_ENABLE      = yes
CAPS_WORD_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
